#!/usr/bin/env python3
"""Build the Nutanix API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'NCM Self-Service': 'NCM SSP',
}

LINES = [
    {
        "name": 'Prism Central',
        "color": '#024DA1',
        "stations": [
        ('Prism Central v3', (310, 200)),
        ('Prism Central v4', (640, 175)),
        ('Prism Element v2', (970, 200)),
        ],
    },
    {
        "name": 'Apps & Cloud',
        "color": '#5A6275',
        "closed": True,
        "stations": [
        ('Karbon', (610, 460)),
        ('NDB', (810, 550)),
        ('NC2', (810, 700)),
        ('NCM Self-Service', (610, 740)),
        ('Foundation', (490, 600)),
        ],
    },
]

URL_OVERRIDES = {
    'Prism Central v3': 'https://apis.apis.io/apis/nutanix/prism-central-v3/',
    'Prism Central v4': 'https://apis.apis.io/apis/nutanix/prism-central-v4/',
    'Prism Element v2': 'https://apis.apis.io/apis/nutanix/prism-element-v2/',
    'Karbon': 'https://apis.apis.io/apis/nutanix/karbon/',
    'NDB': 'https://apis.apis.io/apis/nutanix/ndb/',
    'NC2': 'https://apis.apis.io/apis/nutanix/nc2/',
    'NCM Self-Service': 'https://apis.apis.io/apis/nutanix/ncm-self-service/',
    'Foundation': 'https://apis.apis.io/apis/nutanix/foundation/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Nutanix API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: nutanix/openapi · github.com/api-evangelist/nutanix',
        out_dir=Path(__file__).resolve().parent,
        out_basename='nutanix-subway-map',
        provider_id='nutanix',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
